### ISSUE TITLE
How to obtain absolute orientation?

### ISSUE THREAD

**Issue by PatrickVibild** [adafruit/Adafruit_CircuitPython_BNO055#120]
Hi.

Being struggling with bno055 to obtain an absolute orientation from it.

I notice that even when the sensor is set ut in NDOF mode there is no fusion on the orientation.

```
import adafruit_bno055
import busio
import board
import time


class IMU:
  def __init__(self):
    self.i2c = busio.I2C(board.SCL, board.SDA)
    self.imu_sensor = adafruit_bno055.BNO055_I2C(self.i2c)
    self.imu_sensor.mode = adafruit_bno055.NDOF_MODE

  def get_data(self):
    return self.imu_sensor.quaternion, self.imu_sensor.euler

  def calibrated(self):
    return self.imu_sensor.calibrated, self.imu_sensor.calibration_status

if __name__ == '__main__':
  imu = IMU()
  while True:
    q, e = imu.get_data()
    print(q)
    print(e)
    time.sleep(1)
```

How can I obtain an absolute orientation of the sensor? Do I have to use magnetometer and euler at the same time?

**Comment by FoamyGuy** [comment]
Sorry for the long delay. I believe either the euler angles, or magnetometer readings can be used to obtain the orientation. I'm not sure what you mean by "...there is no fusion on the orientation." I tried searching around for this but I'm finding too many things related to fusion software. 

If you are still having trouble this is better kind of thing to ask on the forums or discord since it's not an issue with the library but rather a question about how to use it.
