### ISSUE TITLE
Reading all zeros

### ISSUE THREAD

**Issue by researcher2312** [adafruit/Adafruit_CircuitPython_BNO055#125]
I have encountered a problem where the device is connected properly, but constantly reads only 0.0 results. The temperature only reads 23, no matter how hot or how cold it gets. The calibration values always read (0, 3, 0, 0). Any resetting or changing modes does not help.

**Comment by dhalbert** [comment]
Which board are you using this with, and which version of CircuitPython?

**Comment by researcher2312** [comment]
![obraz](https://github.com/user-attachments/assets/ab57f6f0-6a5e-4f3f-85ec-5ff1f9d6cd95)
I am running a custom hardware with Raspberry Pi Pico W
CircuitPython 9.1.1

**Comment by FoamyGuy** [comment]
I tested this today with a BNO055 QTPY bff connected to a Raspberry Pi Pico W `9.2.1` I am getting accurate values for temperature and accel / magnetometer.  I am not sure of the root cause of your issues, but I don't think it's a bug in the library. If you are still having this problem please ask for help in the forums or discord. Or if you have identified some issue within the library code related to this feel free to re-open.

**Comment by researcher2312** [comment]
Yes, thank you, probably my sensor unit is damaged and readings are not correct.
