### ISSUE TITLE
[Question] BNO055 compatibility with Legacy RPi OS

### ISSUE THREAD

**Issue by jssaditi** [adafruit/Adafruit_CircuitPython_BNO055#97]
Hello, 
Is the BNO055 sensor and accompanying python module compatible with the Raspberry Pi OS (Legacy)?

**Comment by ladyada** [comment]
hiya, questions about how to use adafruit products are best posted in the adafruit forums  at [forums.adafruit.com](forums.adafruit.com/)
thats where tech support is handled - github issues are where folks can issue bug reports (e.g. something that ought to work but doesnt due to a hardware or software bug)

thanks! :)
